<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="APOORVA" name="WinApp.WindowsCalculator" tests="6" failures="0" timestamp="2020-07-05T12:45:03 IST" time="0.158" errors="1">
  <testcase name="Multiplication" time="0.000" classname="WinApp.WindowsCalculator">
    <skipped/>
  </testcase> <!-- Multiplication -->
  <system-out/>
  <testcase name="Clear" time="0.153" classname="WinApp.WindowsCalculator">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at WinApp.WindowsCalculator.Clear(WindowsCalculator.java:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:64)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:364)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:318)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:620)
at org.testng.TestRunner.beforeRun(TestRunner.java:610)
at org.testng.TestRunner.run(TestRunner.java:581)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Clear -->
  <system-out/>
  <testcase name="Division" time="0.000" classname="WinApp.WindowsCalculator">
    <skipped/>
  </testcase> <!-- Division -->
  <system-out/>
  <testcase name="Combination" time="0.000" classname="WinApp.WindowsCalculator">
    <skipped/>
  </testcase> <!-- Combination -->
  <system-out/>
  <testcase name="Addition" time="0.005" classname="WinApp.WindowsCalculator">
    <skipped/>
  </testcase> <!-- Addition -->
  <system-out/>
  <testcase name="Subtraction" time="0.000" classname="WinApp.WindowsCalculator">
    <skipped/>
  </testcase> <!-- Subtraction -->
  <system-out/>
</testsuite> <!-- WinApp.WindowsCalculator -->
